version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: weather_service
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8888 --reload"
    ports:
      - "8888:8888"
      - "8089:8089"
    volumes:
      - ..:/app
    env_file:
      - ../.env
    depends_on:
      - dynamodb


  dynamodb:
    image: amazon/dynamodb-local
    container_name: weather_service_dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/data


  minio:
    image: minio/minio
    container_name: weather_service_minio
    ports:
      - "9000:9000"       # MinIO console/API access
      - "9001:9001"       # MinIO web admin console
    env_file:
      - ../.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data


volumes:
  minio_data:
  dynamodb_data:
